export const PORT = Number(process.env.PORT) || 3001;
export const MP_ACCESS_TOKEN = process.env.MP_ACCESS_TOKEN || '';
export const MP_PUBLIC_KEY = process.env.MP_PUBLIC_KEY || '';
export const FRONTEND_URL = process.env.FRONTEND_URL || '';
export const MP_WEBHOOK_URL = process.env.MP_WEBHOOK_URL || '';
export const CORS_ALLOWED_ORIGINS = process.env.CORS_ALLOWED_ORIGINS || FRONTEND_URL || '';
export const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID || '';
export const FACEBOOK_APP_ID = process.env.FACEBOOK_APP_ID || '';
export const FACEBOOK_APP_SECRET = process.env.FACEBOOK_APP_SECRET || '';
export const TOKEN_SECRET = process.env.TOKEN_SECRET || 'troque-este-token-secret-em-producao';
export const ADMIN_EMAIL = process.env.ADMIN_EMAIL || 'admin@varejao.com';
export const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || 'admin123456';
export const DEMO_OPERATIONAL_PASSWORD = process.env.DEMO_OPERATIONAL_PASSWORD || '12345678';
export const DISABLE_DEMO_OPERATIONAL_USERS = process.env.DISABLE_DEMO_OPERATIONAL_USERS === 'true';
